# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'product.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt5.QtWidgets import QTableWidgetItem

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(645, 510)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 81, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(90, 10, 301, 171))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_2.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_2.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_2.addWidget(self.lineEdit_6)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(420, 10, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(430, 50, 47, 13))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(430, 70, 71, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(430, 90, 47, 13))
        self.label_9.setObjectName("label_9")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 200, 551, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(10, 250, 181, 16))
        self.label_10.setObjectName("label_10")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(10, 280, 551, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Id"))
        self.label_2.setText(_translate("Form", "Barkode"))
        self.label_3.setText(_translate("Form", "Name"))
        self.label_4.setText(_translate("Form", "Kategori"))
        self.label_6.setText(_translate("Form", "Qty"))
        self.label_5.setText(_translate("Form", "Harga"))
        self.pushButton.setText(_translate("Form", "SEARCH"))
        self.label_7.setText(_translate("Form", "Search"))
        self.label_8.setText(_translate("Form", "Berdasarkan"))
        self.label_9.setText(_translate("Form", "Id"))
        self.pushButton_5.setText(_translate("Form", "INSERT"))
        self.pushButton_4.setText(_translate("Form", "UPDATE"))
        self.pushButton_3.setText(_translate("Form", "DELETE"))
        self.pushButton_2.setText(_translate("Form", "LOAD DATA"))
        self.label_10.setText(_translate("Form", "SATATUS AKAN TERLIHAT DISINI"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "barkode"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "kategori"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "qty"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "harga"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.pushButton.clicked.connect(self.searchProduct) 
        self.pushButton_2.clicked.connect(self.loadProduct)  
        self.pushButton_3.clicked.connect(self.deleteProduct)  
        self.pushButton_4.clicked.connect(self.updateProduct)  
        self.pushButton_5.clicked.connect(self.insertProduct) 

        self.tableWidget.cellClicked.connect(self.getId)

    def insertProduct(self):
        try:
            id = self.lineEdit.text()
            barkode = self.lineEdit_2.text()
            name = self.lineEdit_3.text()
            kategori = self.lineEdit_4.text()
            qty = self.lineEdit_5.text()
            harga = self.lineEdit_6.text()

            if not (id and barkode and name and kategori and qty and harga):
                self.label_10.setText("Fields cannot be empty.")
                return

            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="dbpenjualan"
            )
            cursor = mydb.cursor()
            sql = "INSERT INTO product (id, barkode, name, kategori, qty, harga) VALUES (%s, %s, %s, %s, %s, %s)"
            val = (id, barkode, name, kategori, qty, harga)
            cursor.execute(sql, val)
            mydb.commit()
            self.label_10.setText("Data product berhasil disimpan")
            self.clearFields()
            self.loadProduct() 
        except mc.Error as e:
            self.label_10.setText(f"Error: {e}")

    def updateProduct(self):
        try:
            id = self.lineEdit.text()  # id tetap dari lineEdit
            barkode = self.lineEdit_2.text()
            name = self.lineEdit_3.text()
            kategori = self.lineEdit_4.text()
            qty = self.lineEdit_5.text()
            harga = self.lineEdit_6.text()

            # Validasi input
            if not (id and barkode and name and kategori and qty and harga):
                self.label_6.setText("Fields cannot be empty.")
                return

            # Database connection
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="dbpenjualan"
            )
            cursor = mydb.cursor()

            # Update query
            sql = """UPDATE product 
                SET barkode = %s, name = %s, kategori = %s, qty = %s, harga = %s 
                WHERE id = %s"""
            val = (barkode, name, kategori, qty, harga)
            cursor.execute(sql, val)
            mydb.commit()

            # Feedback
            if cursor.rowcount == 0:
                self.label_10.setText(f"Id {id} tidak ditemukan.")
            else:
                self.label_10.setText("Data product berhasil diperbarui")
                self.loadProduct()  # Refresh data
        except mc.Error as e:
            self.label_10.setText(f"Error: {e}")


    def deleteProduct(self):
        try:
            id = self.lineEdit.text()  # id tetap dari lineEdit
            if not id:
                self.label_10.setText("Id cannot be empty.")
                return

            # Database connection
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="dbpenjualan"
            )
            cursor = mydb.cursor()

            # Delete query
            sql = "DELETE FROM product WHERE id = %s"
            val = (id,)
            cursor.execute(sql, val)
            mydb.commit()

            # Feedback
            if cursor.rowcount == 0:
                self.label_10.setText(f"Id {id} tidak ditemukan.")
            else:
                self.label_10.setText("Data product berhasil dihapus")
                self.loadProduct()  # Refresh data
                self.clearFields()  # Clear input fields
        except mc.Error as e:
            self.label_10.setText(f"Error: {e}")


    def loadProduct(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="dbpenjualan"
            )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT id, barkode, name, kategori, qty, harga FROM product ORDER BY id ASC")
            result = mycursor.fetchall()

            self.tableWidget.setRowCount(0)
            self.tableWidget.setColumnCount(5)  
            self.tableWidget.setHorizontalHeaderLabels(["Id", "Barkode", "Name", "Kategori", "Qty", "Harga"])

            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))

            self.label_10.setText("Data product berhasil ditampilkan")
        except mc.Error as err:
            self.label_10.setText(f"Error: {err}")

    def clearFields(self):
        self.lineEdit.clear()
        self.lineEdit_2.clear()
        self.lineEdit_3.clear()
        self.lineEdit_4.clear()
        self.lineEdit_5.clear()
        self.lineEdit_6.clear()
    
    def getId(self, row, column):
        try:
            id = self.tableWidget.item(row, 0).text()  
            barkode = self.tableWidget.item(row, 1).text()  
            name = self.tableWidget.item(row, 2).text()  
            kategori = self.tableWidget.item(row, 3).text() 
            qty = self.tableWidget.item(row, 4).text() 
            harga = self.tableWidget.item(row, 5).text() 

            self.lineEdit.setText(id)
            self.lineEdit_2.setText(barkode)
            self.lineEdit_3.setText(name)
            self.lineEdit_4.setText(kategori)
            self.lineEdit_5.setText(qty)
            self.lineEdit_6.setText(harga)
            self.label_10.setText("DATA SUDAH DI LOAD.")
        except AttributeError:
            self.label_4.setText("Error: DATA GAGAL DI LOAD.")
    
    def searchMahasiswa(self):
        try:
            id = self.lineEdit.text() 
            if not id:
                self.label_10.setText("Silakan masukkan Id.")
                return

            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="dbpenjualan"
            )
            cursor = mydb.cursor()

            sql = "SELECT id, barkode, name, kategori, qty, harga FROM product WHERE id = %s"
            val = (id,)
            cursor.execute(sql, val)
            result = cursor.fetchone()  

            self.tableWidget.setRowCount(0)
            self.tableWidget.setColumnCount(5)
            self.tableWidget.setHorizontalHeaderLabels(["Id", "Barkode", "Name", "Kategori", "Qty", "Harga"])

            if result:
                self.tableWidget.insertRow(0)
                for column_number, data in enumerate(result):
                    self.tableWidget.setItem(0, column_number, QTableWidgetItem(str(data)))
                self.label_10.setText("Data ditemukan.")
            else:
                self.label_10.setText("Data tidak ditemukan.")
        except mc.Error as e:
            self.label_10.setText(f"Error: {e}")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Id"))
        self.label_2.setText(_translate("Form", "Barkode"))
        self.label_3.setText(_translate("Form", "Name"))
        self.label_4.setText(_translate("Form", "Kategori"))
        self.label_6.setText(_translate("Form", "Qty"))
        self.label_5.setText(_translate("Form", "Harga"))
        self.label_10.setText(_translate("Form", "STATUS AKAN TERLIHAT DISINI"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "barkode"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "kategori"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "qty"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "harga"))
        self.pushButton.setText(_translate("Form", "SEARCH"))
        self.pushButton_2.setText(_translate("Form", "LOAD DATA"))
        self.pushButton_3.setText(_translate("Form", "DELETE"))
        self.pushButton_4.setText(_translate("Form", "UPDATE"))
        self.pushButton_5.setText(_translate("Form", "INSERT"))
        self.label_7.setText(_translate("Form", "Search "))
        self.label_8.setText(_translate("Form", "Berdasarkan"))
        self.label_9.setText(_translate("Form", "NPM"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
